#!/bin/bash
#
# Init file for idega SERVERNAME Tomcat server
#
# chkconfig: 2345 55 25
# description: idega SERVERNAME Tomcat server
#

# Source function library.
. /etc/init.d/functions

RUN-AS-USER=TOMCATUSER # Adjust run user here
CATALINA-HOME=TOMCATSFOLDER/SERVERNAME

start() {
        echo "Starting Tomcat: "
        if [ "x$USER" != "x$RUN-AS-USER" ]; then
          su - $RUN-AS-USER -c "$CATALINA-HOME/bin/startup.sh"
        else
          $CATALINA-HOME/bin/startup.sh
        fi
        echo "done."
}
stop() {
        echo "Shutting down Tomcat: "
        if [ "x$USER" != "x$RUN-AS-USER" ]; then
          su - $RUN-AS-USER -c "$CATALINA-HOME/bin/shutdown.sh"
        else
          $CATALINA-HOME/bin/shutdown.sh
        fi
        echo "done."
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        sleep 10
        #echo "Hard killing any remaining threads.."
        #kill -9 `cat $CATALINA-HOME/work/catalina.pid`
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
esac

exit 0
